let me=null;const $=x=>document.getElementById(x);
function show(x){$("login").classList.toggle("hidden",x!=="login");$("reg").classList.toggle("hidden",x!=="reg");$("app").classList.toggle("hidden",x!=="app")}
function code(){$("rc").classList.toggle("hidden",$("rr").value==="alumno")}
async function api(u,o={}){let r=await fetch(u,{headers:{"Content-Type":"application/json"},...o}),d=await r.json();if(!r.ok)throw Error(d.error||"Error");return d}
async function login(){try{me=await api("/api/login",{method:"POST",body:JSON.stringify({email:$("le").value,password:$("lp").value})});start()}catch(e){$("lm").textContent=e.message}}
async function register(){try{me=await api("/api/register",{method:"POST",body:JSON.stringify({name:$("rn").value,email:$("re").value,password:$("rp").value,role:$("rr").value,code:$("rc").value})});start()}catch(e){$("rm").textContent=e.message}}
function start(){show("app");$("welcome").textContent=`Bienvenido/a ${me.name} · ${me.role}`;nav();home()}
function nav(){$("nav").innerHTML=`<button onclick="home()">Inicio</button><button onclick="horarios()">Horarios</button><button onclick="news()">Noticias</button>${me.role!=="alumno"?'<button onclick="availability()">Avisos</button>':""}${me.role==="alumno"?'<button onclick="opinions()">Opiniones</button>':""}${me.role==="admin"?'<button onclick="admin()">Administración</button>':""}<button onclick="logout()">Salir</button>`}
function home(){$("content").innerHTML=`<div class="panel"><h2>📋 Horarios</h2><p>Consulta la cuadrilla.</p><button onclick="horarios()">Abrir</button></div><div class="panel"><h2>🤖 Chatbot</h2><p>Ayuda con horarios y disponibilidad.</p><button onclick="chat()">Abrir</button></div><div class="panel"><h2>📰 Noticias</h2><p>Actos, reuniones, paros y novedades.</p><button onclick="news()">Ver</button></div>`}
async function horarios(){let d=await api("/api/schedules");$("content").innerHTML=`<div class="panel full"><h2>📋 Cuadrilla</h2>${me.role!=="alumno"?`<input id="st" placeholder="Profesor"><input id="ss" placeholder="Materia"><select id="sd"><option>Lunes</option><option>Martes</option><option>Miércoles</option><option>Jueves</option><option>Viernes</option></select><input id="si" type="time"><input id="se" type="time"><input id="sr" placeholder="Salón"><button onclick="addS()">Agregar horario</button>`:""}<table class="table"><tr><th>Día</th><th>Hora</th><th>Profesor</th><th>Materia</th><th>Salón</th><th></th></tr>${d.map(x=>`<tr><td>${x.day}</td><td>${x.start_time}-${x.end_time}</td><td>${x.teacher}</td><td>${x.subject}</td><td>${x.room}</td><td>${me.role==="admin"?`<button class="danger" onclick="delS(${x.id})">Borrar</button>`:""}</td></tr>`).join("")}</table></div>`}
async function addS(){try{await api("/api/schedules",{method:"POST",body:JSON.stringify({teacher:$("st").value,subject:$("ss").value,day:$("sd").value,start_time:$("si").value,end_time:$("se").value,room:$("sr").value})});horarios()}catch(e){alert(e.message)}}
async function delS(id){await api("/api/schedules/"+id,{method:"DELETE"});horarios()}
async function news(){let d=await api("/api/news");$("content").innerHTML=`<div class="panel full"><h2>📰 Noticias</h2>${me.role==="admin"?`<input id="nt" placeholder="Título"><input id="ny" placeholder="Tipo: acto, reunión, paro..."><textarea id="nc" placeholder="Contenido"></textarea><button onclick="addN()">Publicar</button>`:""}${d.map(x=>`<div class="item"><b>${x.title}</b> · ${x.type}<p>${x.content}</p></div>`).join("")||"<p>No hay noticias.</p>"}</div>`}
async function addN(){await api("/api/news",{method:"POST",body:JSON.stringify({title:$("nt").value,type:$("ny").value,content:$("nc").value})});news()}
async function availability(){let d=await api("/api/availability");$("content").innerHTML=`<div class="panel"><h2>📅 Avisos</h2><input id="as" type="date"><input id="ae" type="date"><input id="ar" placeholder="Motivo"><button onclick="addA()">Guardar</button>${d.map(x=>`<div class="item"><b>${x.teacher}</b><br>${x.start_date} → ${x.end_date}<br>${x.reason}</div>`).join("")}</div>`}
async function addA(){await api("/api/availability",{method:"POST",body:JSON.stringify({start_date:$("as").value,end_date:$("ae").value,reason:$("ar").value})});availability()}
function opinions(){$("content").innerHTML=`<div class="panel"><h2>💬 Opinión</h2><input id="ot" placeholder="Profesor"><textarea id="oc" placeholder="Opinión"></textarea><button onclick="sendO()">Enviar</button></div>`}
async function sendO(){await api("/api/opinions",{method:"POST",body:JSON.stringify({teacher:$("ot").value,content:$("oc").value})});home()}
async function admin(){let [u,o,v]=await Promise.all([api("/api/users"),api("/api/opinions"),api("/api/violations")]);$("content").innerHTML=`<div class="panel full"><h2>🔐 Administración</h2><h3>Usuarios</h3>${u.map(x=>`<div class="item">${x.name} · ${x.email} · ${x.role}</div>`).join("")}<h3>Opiniones</h3>${o.map(x=>`<div class="item"><b>${x.teacher}</b>: ${x.content} · ${x.student}</div>`).join("")}<h3>🚫 Incumplimientos</h3><input id="vt" placeholder="Profesor"><textarea id="vd" placeholder="Descripción"></textarea><button onclick="addV()">Registrar</button>${v.map(x=>`<div class="item"><b>${x.teacher}</b>: ${x.description}</div>`).join("")}</div>`}
async function addV(){await api("/api/violations",{method:"POST",body:JSON.stringify({teacher:$("vt").value,description:$("vd").value})});admin()}
function chat(){$("content").innerHTML=`<div class="panel"><h2>🤖 Chatbot</h2><div id="c" class="chat"><div class="bubble">Hola. Preguntame por horarios, cuadrilla, disponibilidad, noticias u opiniones.</div></div><input id="ci" placeholder="Escribe una pregunta"><button onclick="sendC()">Enviar</button></div>`}
async function sendC(){let q=$("ci").value;$("c").innerHTML+=`<div class="bubble me">${q}</div>`;let d=await api("/api/chatbot",{method:"POST",body:JSON.stringify({message:q})});$("c").innerHTML+=`<div class="bubble">${d.answer}</div>`;$("ci").value=""}
async function logout(){await api("/api/logout",{method:"POST"});location.reload()}
(async()=>{let u=await api("/api/me");if(u){me=u;start()}else show("login")})()